#!/bin/bash
# WORKFLOW FOR SOMATIC GENOMIC ANALYSIS OF MATCHED TUMOR-NORMAL SAMPLES
# --- Tool Paths ---
TOOLS_DIR="/home/humangenomics/Documents/HumanGenomics/Tools"
GATK_JAR="$TOOLS_DIR/GenomeAnalysisTK.jar"
PICARD_JAR="$TOOLS_DIR/picard.jar"
VARSCAN_JAR="$TOOLS_DIR/VarScan.v2.3.9.jar"
SNPEFF_DIR="$TOOLS_DIR/snpEff"
SNPEFF_JAR="$SNPEFF_DIR/snpEff.jar"
SNPSIFT_JAR="$SNPEFF_DIR/SnpSift.jar"

# --- Annotation and Reference Genome Paths ---
ANNOTATIONS_DIR="/home/humangenomics/Documents/HumanGenomics/Annotations"
REF_FASTA="$ANNOTATIONS_DIR/human_g1k_v37.fasta"
CAPTURED_REGIONS="$ANNOTATIONS_DIR/Captured_Regions.bed"
HAPMAP_VCF="$ANNOTATIONS_DIR/hapmap_3.3.b37.vcf"
CLINVAR_VCF="$ANNOTATIONS_DIR/clinvar_Pathogenic.vcf"
CANCER_GENES_BED="$ANNOTATIONS_DIR/CancerGenesSel.bed"

# --- R Scripts ---
CBS_SCRIPT="./CBS.R"
CLONET_SCRIPT="./CLONET.R"

# --- Realignment ---
java -jar $GATK_JAR -T \
RealignerTargetCreator -R $REF_FASTA -I Tumor.sorted.bam -o Tumor.realigner.intervals -L $CAPTURED_REGIONS

java -jar $GATK_JAR -T \
RealignerTargetCreator -R $REF_FASTA -I Control.sorted.bam -o Control.realigner.intervals -L $CAPTURED_REGIONS

java -jar $GATK_JAR -T IndelRealigner -R $REF_FASTA \
 -I Tumor.sorted.bam -targetIntervals Tumor.realigner.intervals -o Tumor.sorted.realigned.bam -L $CAPTURED_REGIONS

java -jar $GATK_JAR -T IndelRealigner -R $REF_FASTA \
-I Control.sorted.bam -targetIntervals Control.realigner.intervals -o Control.sorted.realigned.bam -L $CAPTURED_REGIONS

# --- Recalibration ---
java -jar $GATK_JAR -T BaseRecalibrator -R $REF_FASTA \
-I Tumor.sorted.realigned.bam -knownSites $HAPMAP_VCF -o recal.table.Tumor -L $CAPTURED_REGIONS

java -jar $GATK_JAR -T BaseRecalibrator -R $REF_FASTA \
-I Control.sorted.realigned.bam -knownSites $HAPMAP_VCF -o recal.table.Control -L $CAPTURED_REGIONS

java -jar $GATK_JAR -T PrintReads -R $REF_FASTA -I \
Tumor.sorted.realigned.bam -BQSR recal.table.Tumor -o Tumor.sorted.realigned.recalibrated.bam -L $CAPTURED_REGIONS --emit_original_quals

java -jar $GATK_JAR -T PrintReads -R $REF_FASTA -I \
Control.sorted.realigned.bam -BQSR recal.table.Control -o Control.sorted.realigned.recalibrated.bam -L $CAPTURED_REGIONS --emit_original_quals

java -jar $GATK_JAR -T BaseRecalibrator -R $REF_FASTA \
-I Tumor.sorted.realigned.bam -knownSites $HAPMAP_VCF -BQSR recal.table.Tumor -o after_recal.table.Tumor -L $CAPTURED_REGIONS

java -jar $GATK_JAR -T BaseRecalibrator -R $REF_FASTA \
-I Control.sorted.realigned.bam -knownSites $HAPMAP_VCF -BQSR recal.table.Control -o after_recal.table.Control -L $CAPTURED_REGIONS

java -jar $GATK_JAR -T AnalyzeCovariates -R $REF_FASTA -before recal.table.Tumor -after after_recal.table.Tumor -csv recal.Tumor.csv -plots recal.Tumor.pdf && \
java -jar $GATK_JAR -T AnalyzeCovariates -R $REF_FASTA -before recal.table.Control -after after_recal.table.Control -csv recal.Control.csv -plots recal.Control.pdf

# --- Deduplication ---
java -jar $PICARD_JAR MarkDuplicates I=Control.sorted.realigned.recalibrated.bam O=Control.sorted.realigned.recalibrated.debup.bam REMOVE_DUPLICATES=true TMP_DIR=/tmp METRICS_FILE=Control.picard.log ASSUME_SORTED=true && \
java -jar $PICARD_JAR MarkDuplicates I=Tumor.sorted.realigned.recalibrated.bam O=Tumor.sorted.realigned.recalibrated.debup.bam REMOVE_DUPLICATES=true TMP_DIR=/tmp METRICS_FILE=Tumor.picard.log ASSUME_SORTED=true

samtools index Tumor.sorted.realigned.recalibrated.debup.bam
samtools index Control.sorted.realigned.recalibrated.debup.bam

# --- Somatic copy number ---
samtools mpileup -q 1 -f $REF_FASTA Control.sorted.realigned.recalibrated.debup.bam Tumor.sorted.realigned.recalibrated.debup.bam | java -jar $VARSCAN_JAR copynumber --output-file SCNA --mpileup 1 && \
java -jar $VARSCAN_JAR copyCaller SCNA.copynumber --output-file SCNA.copynumber.called

Rscript $CBS_SCRIPT

awk 'BEGIN{OFS="\t"} NR>1 {print $2, $3, $4, $6}' SCNA.copynumber.called.seg > SCNA.segments.for_annotation.bed

bedtools intersect -a SCNA.segments.for_annotation.bed -b $CANCER_GENES_BED -wa -wb > SCNA.annotated_with_genes.txt

# --- Identifying variants with bcftools and GATK ---
bcftools mpileup -Ou -a DP -f $REF_FASTA Control.sorted.realigned.recalibrated.debup.bam | bcftools call -Ov -c -v > Control.BCF.vcf && \
bcftools mpileup -Ou -a DP -f $REF_FASTA Tumor.sorted.realigned.recalibrated.debup.bam | bcftools call -Ov -c -v > Tumor.BCF.vcf && \
java -jar $GATK_JAR -T UnifiedGenotyper -R $REF_FASTA -I Control.sorted.realigned.recalibrated.debup.bam -o Control.GATK.vcf -L $CAPTURED_REGIONS && \
java -jar $GATK_JAR -T UnifiedGenotyper -R $REF_FASTA -I Tumor.sorted.realigned.recalibrated.debup.bam -o Tumor.GATK.vcf -L $CAPTURED_REGIONS

vcftools --minQ 20 --min-meanDP 30 --remove-indels --vcf Tumor.BCF.vcf --out Tumor.BCF --recode --recode-INFO-all
vcftools --minQ 20 --min-meanDP 30 --remove-indels --vcf Control.BCF.vcf --out Control.BCF --recode --recode-INFO-all
vcftools --minQ 20  --min-meanDP 30 --remove-indels --vcf Control.GATK.vcf --out Control.GATK --recode --recode-INFO-all
vcftools --minQ 20  --min-meanDP 30 --remove-indels --vcf Tumor.GATK.vcf --out Tumor.GATK --recode --recode-INFO-all

vcftools --vcf Control.BCF.recode.vcf --diff Control.GATK.recode.vcf --diff-site
vcftools --vcf Tumor.BCF.recode.vcf --diff Tumor.GATK.recode.vcf --diff-site

# --- Annotation ---
# - from BCF
java -Xmx4g -jar $SNPEFF_JAR -v hg19kg Control.BCF.recode.vcf -s Control.BCF.recode.ann.html > Control.BCF.recode.ann.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $HAPMAP_VCF Control.BCF.recode.ann.vcf > Control.BCF.recode.ann2.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $CLINVAR_VCF Control.BCF.recode.ann2.vcf > Control.BCF.recode.ann3.vcf && \
java -Xmx4g -jar $SNPEFF_JAR -v hg19kg Tumor.BCF.recode.vcf -s Tumor.BCF.recode.ann.html > Tumor.BCF.recode.ann.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $HAPMAP_VCF Tumor.BCF.recode.ann.vcf > Tumor.BCF.recode.ann2.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $CLINVAR_VCF Tumor.BCF.recode.ann2.vcf > Tumor.BCF.recode.ann3.vcf

# - from GATK
java -Xmx4g -jar $SNPEFF_JAR -v hg19kg Control.GATK.recode.vcf -s Control.GATK.recode.ann.html > Control.GATK.recode.ann.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $HAPMAP_VCF Control.GATK.recode.ann.vcf > Control.GATK.recode.ann2.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $CLINVAR_VCF Control.GATK.recode.ann2.vcf > Control.GATK.recode.ann3.vcf && \
java -Xmx4g -jar $SNPEFF_JAR -v hg19kg Tumor.GATK.recode.vcf -s Tumor.GATK.recode.ann.html > Tumor.GATK.recode.ann.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $HAPMAP_VCF Tumor.GATK.recode.ann.vcf > Tumor.GATK.recode.ann2.vcf && \
java -Xmx4g -jar $SNPSIFT_JAR Annotate $CLINVAR_VCF Tumor.GATK.recode.ann2.vcf > Tumor.GATK.recode.ann3.vcf

# --- Filtering .vcf files ---
cat Control.BCF.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(ANN[ANY].IMPACT = 'HIGH') & (DP > 20) & (exists ID)" && \
cat Control.GATK.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(ANN[ANY].IMPACT = 'HIGH') & (DP > 20) & (exists ID)" && \
cat Control.BCF.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(exists CLNSIG)" && \
cat Control.GATK.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(exists CLNSIG)" && \
cat Tumor.BCF.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(ANN[ANY].IMPACT = 'HIGH') & (DP > 20) & (exists ID)" && \
cat Tumor.GATK.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(ANN[ANY].IMPACT = 'HIGH') & (DP > 20) & (exists ID)" && \
cat Tumor.BCF.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(exists CLNSIG)" && \
cat Tumor.GATK.recode.ann3.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(exists CLNSIG)"

# --- Somatic variant calling ---
samtools mpileup -q 1 -f $REF_FASTA Control.sorted.realigned.recalibrated.debup.bam > Control.sorted.pileup && \
samtools mpileup -q 1 -f $REF_FASTA Tumor.sorted.realigned.recalibrated.debup.bam > Tumor.sorted.pileup

java -jar $VARSCAN_JAR somatic Control.sorted.pileup Tumor.sorted.pileup --output-snp somatic.pm --output-indel somatic.indel --output-vcf 1 && \
java -jar $VARSCAN_JAR somatic Control.sorted.pileup Tumor.sorted.pileup --output-snp somatic.pm --output-indel somatic.indel

# - Annotation
java -Xmx4g -jar $SNPSIFT_JAR Annotate $HAPMAP_VCF somatic.pm.vcf > somatic.pm.vcf.hapmap_ann.vcf

# - Filtering vcf
cat somatic.pm.vcf.hapmap_ann.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "(exists ID) & ( ID =~ 'rs' )" > somatic.pm.onlySNPs.vcf && \
cat somatic.pm.vcf.hapmap_ann.vcf | java -Xmx4g -jar $SNPSIFT_JAR filter "!(exists ID) & !( ID =~ 'rs' )" > somatic.pm.noSNPs.vcf

# --- Purity Ploidy ---
bcftools mpileup -Ou -a DP -f $REF_FASTA Control.sorted.realigned.recalibrated.debup.bam | bcftools call -Ov -c -v > Control.BCF.vcf && \
bcftools mpileup -Ou -a DP -f $REF_FASTA Tumor.sorted.realigned.recalibrated.debup.bam | bcftools call -Ov -c -v > Tumor.BCF.vcf && \
grep -E "(^#|0/1)" Control.BCF.vcf > Control.het.vcf && \
grep -E "(^#|0/1)" Tumor.BCF.vcf > Tumor.het.vcf && \
java -jar $GATK_JAR -T ASEReadCounter -R $REF_FASTA \
-o recal.Control.csv -I Control.sorted.realigned.recalibrated.debup.bam -sites \
Control.het.vcf -U ALLOW_N_CIGAR_READS \
-minDepth 20 \
--minMappingQuality 20 \
--minBaseQuality 20 && \
java -jar $GATK_JAR -T ASEReadCounter \
-R $REF_FASTA \
-o Tumor.csv \
-I Tumor.sorted.realigned.recalibrated.debup.bam -sites \
Control.het.vcf -U ALLOW_N_CIGAR_READS \
-minDepth 20 \
--minMappingQuality 20 \
--minBaseQuality 20

Rscript $CLONET_SCRIPT

java -jar $GATK_JAR \
-T ASEReadCounter \
-R $REF_FASTA \
-o recal.Control2.csv \
-I Control.sorted.realigned.recalibrated.debup.bam \
-sites $HAPMAP_VCF \
-U ALLOW_N_CIGAR_READS \
-minDepth 20 \
--minMappingQuality 20 \
--minBaseQuality 20 \
&& \
java -jar $GATK_JAR \
-T ASEReadCounter \
-R $REF_FASTA \
-o Tumor2.csv \
-I Tumor.sorted.realigned.recalibrated.debup.bam \
-sites $HAPMAP_VCF \
-U ALLOW_N_CIGAR_READS \
-minDepth 20 \
--minMappingQuality 20 \
--minBaseQuality 20
